
###Test create user
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "username": "toan12345",
    "password": "12345678",
    "full_name": "Toan dep trai",
    "email" : "toandz4101998@gmail.com"
}
###Test get user
GET  http://localhost:9090/user/toan12345 HTTP/1.1
Authorization: Bearer v2.llU7ExLwai1EhiNJjSLwjfn6m_UkuVGyngEbsWoT06aPG3_e1yVnj-KJ5ypBoaUjeK_cpJAkRVXctDfdfmckXnM8fHUNEzROvtWVJCyDoAuTiRiTHd5MxllC3Cn60DiiNyCgD4HubeEGFkek_36Hyyx__B_AgmmI52p95axZV2sf0pqvIax41AkUEJxph38uC4ioCPQsN31GjCcZkBZzm6bkCyo0m8laJkmLoI_78CF9e3VnbkVjZVxAkK6ygxRlZ1NMbomzgI4gNpHupn9oKlAdLmB5Dujx.bnVsbA
content-type: application/json
###TestPostLogin
POST http://localhost:9090/user/login HTTP/1.1
content-type: application/json

{
    "username": "toan12345",
    "password": "12345678"
}
###TestRenewToken 
POST http://localhost:9090/token/renew HTTP/1.1
content-type: application/json

{
    "refresh_token": "v2.local.npwTlVI3xhi3cHyzx4lrVRJo6Qj5R2cPfeKOcpDY9nFaBqV0Vs6F5wi82hNkoV_CMHoeDA2J5pG064E50b-ED0gsBtoAm-RQ-LTew0yf0PtWO-SRTeUPgi9O8radIGmLd5a2B7ikT6ow1zhzLJJ_i9A7kP0TYWXdU-oGHr1dKyafkVkl_hRoOqtYNMeP4wegJesDQXwSTsgWB0kW0Xmme_RL2_DCQgxtf23L4cBPOXr3InSW3cHmKu9JtPcMs3oMsr-5krr9Jjd9JQMJcs3FXI5MgPTAOlZ6DHp7.bnVsbA"
}


